on:
  push:
    branches:
      - main
  pull_request:
  
name: automatedTests

jobs:
  automatedTests:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/automated_tests_template.yaml@main
    