on:
  push:
    branches:
      - main
      - development
  pull_request:
      
name: deployShinyApps

jobs:
  deploy-shiny:
     uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard_deploy_template.yaml@main
