on:
  push:
    branches:
      - main
      - development

name: deployShinyApps

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with: 
         r-version: '4.4.0'
         
      - name: Set env vars (dev)
        if: endsWith(github.ref, '/development')
        run: |
          echo "SHINYAPP_NAME='dev-la-school-places-scorecards'" >> $GITHUB_ENV
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/main')
        run: |
          echo "SHINYAPP_NAME='la-school-places-scorecards'">> $GITHUB_ENV

      - name: Install Curl
        run: sudo apt install libcurl4-openssl-dev libssl-dev
        
      - name: Cache renv packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
        
      - name: Restore renv snapshot
        shell: Rscript {0}
        run: |
          if (!require('renv')) install.packages('renv')
          renv::restore()
      - name: Push to shiny.io
        run: >
          Rscript
          -e "rsconnect::setAccountInfo(name='department-for-education', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')"
          -e "rsconnect::deployApp(appName=${{env.SHINYAPP_NAME}}, forceUpdate = TRUE)"
