on:
  push:
    branches:
      - main
      - development
  pull_request:
      
name: Deploy Shiny dashboard

jobs:
  deploy-shiny:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard_deploy_template.yaml@main
    with:
      parameter_file: deploy-parameters.yaml
    secrets:
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      
