on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '20 3 * * 0'

name: lintr

jobs:
  lint:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/lintr_reusable.yaml@main
    with:
      is_package: "false"
    secrets:
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      